sudo: required

language: csharp

branches:
  only:
  - master

services:
  - docker

script:
  - chmod ugo+x ./dockerClean.sh
  - chmod ugo+x ./start-db.sh
  - chmod ugo+x ./start-web.sh
  - ./dockerClean.sh
  - ./start-db.sh
  - ./start-web.sh