sudo: required

language: csharp

branches:
  only:
  - master

services:
  - docker

script:
  - sudo chmod +x start-db.sh
  - sudo chmod +x start-web.sh
  - sudo sh start-db.sh
  - sudo sh start-web.sh